player_get_players_display:
    path:     /display_players/{pageIndex}
    defaults:
        _controller: "QuidditchBundle:Player:getPlayersDisplay"
        pageIndex: 1
    methods:  [GET, POST]

player_show:
    path:     /{id}/show
    defaults: { _controller: "QuidditchBundle:Player:show" }
    methods:  GET

player_new:
    path:     /new
    defaults: { _controller: "QuidditchBundle:Player:new" }
    methods:  [GET, POST]

player_edit:
    path:     /{id}/edit
    defaults: { _controller: "QuidditchBundle:Player:edit" }
    methods:  [GET, POST]

player_delete:
    path:     /{id}/delete
    defaults: { _controller: "QuidditchBundle:Player:delete" }
    methods:  DELETE

player_index:
    path:     /
    defaults:
        _controller: "QuidditchBundle:Player:index"
    methods:  GET
